### ISSUE TITLE
Thumbnail Carousel- Alignment

### ISSUE THREAD

**Issue by adam-s-p-** [itsMakeable/mbfirm.com---MARKUP#13]
Sometimes the carousel of thumbnails appears to not be vertically aligned.
![image](https://cloud.githubusercontent.com/assets/9142185/13472563/7250fefc-e083-11e5-8c07-ee737df97633.png)

**Comment by mike3run** [comment]
Please elaborate on that issue

**Comment by adam-s-p-** [comment]
The carousel is not vertically aligned on the page.
If you look at the space between Larry and Spencer, it is not vertically aligned with the quote container above it.

**Comment by mike3run** [comment]
Is not because of the fixed sizes of the partners thumbnails, so it just works fine on the specified breakpoints.

I think it has to do more with the carousel plugin but then again we could try it again once we get some container measures:

[See Issue 33](https://github.com/itsMakeable/mbfirm.com/issues/33)
