### ISSUE TITLE
Contact Information- About Page

### ISSUE THREAD

**Issue by adam-s-p-** [itsMakeable/mbfirm.com---MARKUP#30]
Can we make the contact information stick where it is as the user scrolls down the page?
It should go under the quote container and stop before it reaches the Client Testimonial.

**Comment by mike3run** [comment]
That would cause some responsive issues since changing the element to fixed then it wouldn't respect the grid. 

And it would need more JS libraries to pull the trick. specifically:
http://scrollmagic.io/
https://greensock.com/tweenmax

It goes a little bit beyond the scope of the original quotation.

**Comment by adam-s-p-** [comment]
Okay, I will think this over.

**Comment by kylamedina** [comment]
@adam-s-p- please test.

**Comment by adam-s-p-** [comment]
Between 1200px and 1024px the contact information hangs left of the quote container.
![image](https://cloud.githubusercontent.com/assets/9142185/13784833/2129ff8c-eaa7-11e5-8da0-dd47d73baf60.png)

**Comment by adam-s-p-** [comment]
Score!
